Feature/status priority epic
DenyingMad/nota-tabula-front pull request #10
Opened 2021-04-18 18:04 UTC by Yesquero

Слияние функционала изменения статуса и приоритета.

2021-04-19 05:22 UTC, DenyingMad requested changes
Необходимо разрешить конфликт с веткой main

2021-04-19 05:22 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +export const updateStatus = (taskId, newStatus) =>
Вынеси в TaskApi.jsx

2021-04-19 05:22 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +export const updatePriority = (taskId, newPriority) =>
Вынеси в taskApi

2021-04-19 05:22 UTC, DenyingMad commented on src/utils/taskStatusLookup.js
> +export  class TaskStatus {
Почему бы не сделать объект, изменение которого запрещено, в качестве enum. Тогда в остальном коде можно будет обращаться к полям этого объекта, а не хардкодить строки. Например: https://stackoverflow.com/a/5040502

2021-04-19 05:22 UTC, DenyingMad commented on src/components/taskInlined/taskComponents/PrioritySelect.jsx
> +                <option value={"LOW"}>Low</option>
Для приоритета можно создать enum по аналогии со статусом

2021-04-19 13:45 UTC, Yesquero commented on src/utils/taskStatusLookup.js
> +export  class TaskStatus {
Я реализовал возможный enum, но я так же хочу использовать TaskStatus класс как посредник между статусом, который приходит с сервера и всеми возможными компонентами, где будет использоваться статус.

2021-04-19 13:46 UTC, Yesquero commented on src/components/taskInlined/taskComponents/PrioritySelect.jsx
> +                <option value={"LOW"}>Low</option>
Как решим какой будет реализация для enum для статусов - сделаю по аналогии приоритеты.

2021-04-25 16:32 UTC, DenyingMad approved these changes

2021-04-25 16:32 UTC, merged