Исправлено отображение общего количества задач и списков задач при их…
DenyingMad/nota-tabula-front pull request #13
Opened 2021-04-24 17:31 UTC by Yesquero

… удалении/добавлении.

2021-04-24 20:31 UTC, DenyingMad requested changes

2021-04-24 20:31 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +
Стоит вынести логику в Epic.jsx

2021-04-24 20:31 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +
Одна и та же функция

2021-04-24 20:31 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +                totalTaskLists={totalTaskLists}
Значения этих пропов есть в epicDetails, поэтому totalTasls и totalTaskLists можно не передавать, если корректно обновлять epicData.details.totalTasks и epicData.details.totalTaskLists

2021-04-24 20:31 UTC, DenyingMad commented on src/components/taskGroupList/TaskAccordion.jsx
> +    };
Также стоит заменить одним унифицированным методом, т.к. одинаковый функционал

2021-04-24 23:22 UTC, Yesquero commented on src/components/epic/EpicView.jsx
> +
Тогда придется в EpicView передавать и epicData и epicDetails, так-же скорее всего возникнет та-же проблема что и со стейтом для taskLists, т.е. компонент не будет обновляться при изменении стейта.

2021-04-25 07:44 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +
EpicData легко разбивается на epicDetails и taskLists, тогда нам останется передавать по отдельности epicDetails, taskLists и id, если вынести стейты на уровень выше ничего не сломается, протестировал, работает.

2021-04-25 08:39 UTC, DenyingMad requested changes

2021-04-25 08:39 UTC, DenyingMad commented on src/components/epic/rightContainer/TabCoomponents/TaskGroupTab.jsx
> +        props.changeTotalTaskLists(-1, tasksInList * -1);
Странная реализация, мне нужно объяснение того, что тут происходит.
Если код перестает быть читаемым, то это плохо, нужно упрощать.

2021-04-25 08:39 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +    };
Перенос логики актуален

2021-04-25 08:39 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +    };
Я предлагаю свою реализацию из ветки bugfix/total-task-2, можешь смержить эти изменения в свою ветку.

2021-04-25 11:44 UTC, Yesquero commented on src/components/epic/rightContainer/TabCoomponents/TaskGroupTab.jsx
> +        props.changeTotalTaskLists(-1, tasksInList * -1);
При удалении тасклиста обновляются и количество тасклистов и количество задач.

2021-04-25 13:40 UTC, DenyingMad approved these changes

2021-04-25 13:40 UTC, merged