Feature/epic
DenyingMad/nota-tabula-front pull request #6
Opened 2021-04-08 02:37 UTC by Yesquero

Нужен ревью рефактора эпика.

2021-04-09 22:37 UTC, DenyingMad requested changes

2021-04-09 22:37 UTC, DenyingMad commented on package.json
> +  },
Пустой блок dev зависимостей

2021-04-09 22:37 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +// export const createEpic = () => {
Неиспользуемые заглушки нужно удалить. Комментированный код не должен попадать в прод!

2021-04-09 22:37 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +        body: JSON.stringify(taskName)
Если в теле передается json, то используем заголовки запросов для json

2021-04-09 22:37 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +export const createTaskList =(uuid) =>
При создании таск листа мы решили передавать его имя в теле запроса

2021-04-09 22:37 UTC, DenyingMad commented on src/api/EpicDataStubApi.jsx
> +const epicDataDefault = {
Этот код где-нибудь используется? Мы вроде как сняли эту заглушку. Убрать

2021-04-09 22:37 UTC, DenyingMad commented on src/pages/dashboard/Dashboard.jsx
> +    const handlerCreateEpic = () => {
Предлагаю вынести хендлер вне компонента

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +    const handlerAddTaskList = (epicId) => {
Создание и хранение группы задач должно происходить в компоненте rightContainer, там где и располагается список задач
```suggestion
    const handlerAddTaskList = (epicId) => {
```

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +    const [taskLists, setTaskLists] = useState(props.epicData.taskLists);
Должно находиться в правом контейнере

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/leftContainer/LeftContainer.jsx
> +
Где вызов метода api?

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/EpicStyles.js
> +        // maxWidth: "74rem",
Комментарии не должны попадать в код

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/rightContainer/RightContainer.jsx
> +                        }
Вынести в отдельный компонент

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/rightContainer/RightContainer.jsx
> +                </div>
Каждая вкладка переключателя - в отдельный компонент

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/leftContainer/epicInfo/EpicInfo.jsx
> +        >
В одну строчку

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/rightContainer/RightContainerStyles.js
> +        // maxWidth: "73.5rem",
Почистить закомментированные и неиспользуемые стили

2021-04-09 22:37 UTC, DenyingMad commented on src/components/epic/rightContainer/RightContainer.jsx
> +        <div className={clsx(classes.flexColumn, classes.epicRightSide)}>
Разделить логику и представление

2021-04-09 22:37 UTC, DenyingMad commented on src/components/harness/HarnessStyles.js
> +    root: {
Похоже на глобальный стиль

2021-04-09 22:37 UTC, DenyingMad commented on src/components/harness/HarnessStyles.js
> +    rootDrawer: {
Зачем повтор стилей?

2021-04-09 22:37 UTC, DenyingMad commented on src/components/harness/HarnessStyles.js
> +    hide: {
В глобальные

2021-04-09 22:37 UTC, DenyingMad commented on src/components/harness/HarnessView.jsx
>  const HarnessView = (props) => {
Разделить логику и представление

2021-04-09 22:37 UTC, DenyingMad commented on src/components/harness/HarnessView.jsx
> +const LeftToolBar = (props) => {
Возможно стоит вынести в отдельный файл

2021-04-09 22:37 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupList.jsx
> +export const TaskGroupList = (props) => {
Разделить логику и представление

2021-04-09 22:37 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupList.jsx
> +                                    {/*<MenuItem onClick={handlerCrudActions}>Rename</MenuItem>*/}
Почему закомментировано?

2021-04-09 22:37 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupList.jsx
> +    const [editingArray, setEditing] = useState(makeTaskListArray(props.taskLists));
Зачем?

2021-04-09 22:37 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupList.jsx
> +const makeTaskListArray = taskLists => {
Зачем?

2021-04-09 22:37 UTC, DenyingMad commented on src/components/taskList/AddTaskForm.jsx
> +
Лишняя пустая строка

2021-04-09 22:37 UTC, DenyingMad commented on src/components/taskList/AddTaskForm.jsx
> +        console.log(taskName);
Убрать логи

2021-04-09 22:37 UTC, DenyingMad commented on src/pages/dashboard/DashboardStyles.js
> +        // maxWidth: "80rem",
Удалить, если не используется

2021-04-12 07:43 UTC, Yesquero commented on src/components/epic/EpicView.jsx
> +    const handlerAddTaskList = (epicId) => {
Если создание и хранения группы задач происходит в RightContainer то при изменении state task group добавляется, но на клиенте компонент не реднерится заново. Пока оставил как было.

2021-04-12 07:45 UTC, Yesquero commented on src/components/harness/HarnessStyles.js
> +    hide: {
Этот стиль используется только для drawerа и скорее всего нигде больше использоваться не будет (зачем другим кнопкам слева марждин 36?)

2021-04-13 10:38 UTC, DenyingMad requested changes

2021-04-13 10:38 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +        method:"POST",
Не соблюдаешь принципы форматирования, почаще используй Ctrl+Alt_L

2021-04-13 10:38 UTC, DenyingMad commented on src/api/EpicApi.jsx
> +
Лишние пустые строки

2021-04-13 10:38 UTC, DenyingMad commented on src/pages/dashboard/Dashboard.jsx
> +                    classes.addEpicButton
Не нахожу класс addEpicButton: "Unresolved variable addEpicButton"

2021-04-13 10:38 UTC, DenyingMad commented on src/components/epic/EpicView.jsx
> +    const handlerAddTaskList = (epicId) => {
Реализовал возможный вариант в ветке feature/epic-task-group. Ознакомься

2021-04-13 10:38 UTC, DenyingMad commented on src/components/taskList/TaskList.jsx
> +export const TaskList = (props) => {
Исправить форматирование для всех файлов в ветке:
1. Точка с запятой после функций, return и тд
2. Блок return выделять пустой строкой сверху
3. Каждый блок логики, ответственный за один функционал выделять пустыми строками от остальных блоков кода сверху и снизу:

```
export const Component = () => {
    useStylesImport1();
    useStylesImport2();
            
    useState1();
    useState2();
    useState3();
            
    onClickHandle();
    onChangeHandle();
            
    return ();
};

```
4. В конце каждого файла должна быть одна пустая строка

2021-04-13 10:38 UTC, DenyingMad commented on src/components/harness/HarnessStyles.js
> +    hide: {
Имеется ввиду класс hide, у нас могут быть скрытые элементы по всему проекту

2021-04-13 10:38 UTC, DenyingMad commented on src/components/epic/leftContainer/LeftContainerView.jsx
> +                    value={props.epicDetails.epicName === null ? "name is null" : props.epicDetails.epicName}
name is null заменить на более информативную запись

2021-04-13 10:38 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupListStyles.js
> +    removeButton: {
Повтор стиля display: "none". Мне кажется, стоит вынести в глобальные стили с названием hidden

2021-04-13 10:38 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupListStyles.js
> +    },
Стиль width: "100%" используется и в других стилях, поэтому стоит вынести его в глобальные с названием full-width

2021-04-13 10:38 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupListStyles.js
> +    },
Также заменить вхождения этого стиля в другие компоненты на глобальный класс

2021-04-13 10:38 UTC, DenyingMad commented on src/pages/dashboard/Dashboard.jsx
> +export const Dashboard = (props) => {
На данный момент Dashboard не содержит большой логики, но в дальнейшем она разрастется. Предлагаю разделить логику и представление

2021-04-13 10:38 UTC, DenyingMad commented on src/components/taskGroupList/TaskGroupListStyles.js
> +    },
UPD: нашел класс fullWidth в глобальных стилях

2021-04-13 10:38 UTC, DenyingMad commented on src/styles/GlobalStyles.js
> +    addItemButton: {
submitButton и addItemButton одинаковые, за исключением цвета. Если важно сохранить цвет, то его можно вынести в специальный класс, который будет описывать только цвет для кнопки, тогда оставить только один класс, отвечающий за внешний вид кнопки. 
Это относится к принципам БЭМ, разработанных Яндексом, подробнее можно почитать здесь: https://ru.bem.info/methodology/quick-start/

2021-04-13 19:40 UTC, DenyingMad requested changes
Нужно поправить HarnessStyles

2021-04-13 19:40 UTC, DenyingMad commented on src/components/harness/HarnessStyles.js
> +    hide: {
Актуально

2021-04-13 19:40 UTC, DenyingMad commented on src/components/harness/HarnessStyles.js
> +    rootDrawer: {
Актуально

2021-04-15 10:34 UTC, DenyingMad approved these changes

2021-04-15 10:35 UTC, merged